name: Docker Test

on:
  workflow_dispatch:
    
jobs:
  twitter_scan:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/t145/docker-test:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Scan with snscrape
        run: |
          snscrape --jsonl twitter-user Certego_Intel
