name: Docker Test

on:
  workflow_dispatch:
    
jobs:
  twitter_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Scan with snscrape
        run: |
          snscrape --max-results 100 twitter-hashtag archiveteam